apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: june19-norhoai-app-tekton
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/june19-norhoai/overlays/tekton
    repoURL: https://github.com/jdubrick-ai/june19-norhoai-gitops.git
    targetRevision: main
  destination:
    namespace: rhdh-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
